AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::LanguageExtensions
Description: >
  Creates Bedrock Application Inference Profiles for TravelChatBot and InsuranceChatBot using NOVA models.

Parameters:
  pTravelModelSource:
    Type: String
    Description: >
      The Foundation Model ARN for the TravelChatBot.
    Default: arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-pro-v1:0

  pInsuranceModelSource:
    Type: String
    Description: >
      The Foundation Model ARN for the InsuranceChatBot.
    Default: arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-pro-v1:0

Resources:
  TravelChatBotInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub "${AWS::StackName}-TravelChatBot"
      Description: Inference profile for the Travel ChatBot NOVA
      ModelSource:
        CopyFrom: !Ref pTravelModelSource
      Tags:
        - Key: Application
          Value: TravelChatBotNOVA
        - Key: CostCenter
          Value: Travel

  InsuranceChatBotInferenceProfile:
    Type: AWS::Bedrock::ApplicationInferenceProfile
    Properties:
      InferenceProfileName: !Sub "${AWS::StackName}-InsuranceChatBot"
      Description: Inference profile for the Insurance ChatBot NOVA
      ModelSource:
        CopyFrom: !Ref pInsuranceModelSource
      Tags:
        - Key: Application
          Value: InsuranceChatBotNOVA
        - Key: CostCenter
          Value: Insurance

  TravelChatBotParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /bedrock/inference-profiles/TravelChatBotNOVA
      Description: ARN for the TravelChatBot inference profile.
      Type: String
      Value: !Sub "${TravelChatBotInferenceProfile}"
      Tags:
        Application: TravelChatBotNOVA
        CostCenter: Travel

  InsuranceChatBotParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /bedrock/inference-profiles/InsuranceChatBotNOVA
      Description: ARN for the InsuranceChatBot inference profile.
      Type: String
      Value: !Sub "${InsuranceChatBotInferenceProfile}"
      Tags:
        Application: InsuranceChatBotNOVA
        CostCenter: Insurance

Outputs:
  TravelChatBotInferenceProfileArn:
    Description: ARN of the TravelChatBot Inference Profile
    Value: !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:application-inference-profile/${TravelChatBotInferenceProfile}"
  InsuranceChatBotInferenceProfileArn:
    Description: ARN of the InsuranceChatBot Inference Profile
    Value: !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:application-inference-profile/${InsuranceChatBotInferenceProfile}"
